### ISSUE TITLE
Add error return values to a range of methods

### ISSUE THREAD

**Issue by airtonix** [yohamta/donburi#10]
I think we need to return potential errors from these two (there might be others but so far these are the ones I've encountered)

`func (e *Entry) Get[T any](e *Entry, ctype *component.ComponentType) (*T, error)`

`func (cs *SimpleStorage) Component(archetypeIndex ArchetypeIndex, componentIndex ComponentIndex) (unsafe.Pointer, error)` 

My reasons:

I have a System (A draw system) that wants to sort the entities by their Position.Z before rendering them. So it needs to operate a single collection of entities. I think I'm unable to achieve the z sorting i want while they are two separate queries.

```golang
func NewTitleScene(c *core.Core) *TitleScene {
	return &TitleScene{
		Scene: core.Scene{
			World: donburi.NewWorld(),
			Systems: []core.SceneSystem{
				system.NewAnimationSystem(c),
				system.NewDrawSystem(c),
				system.NewCursorSystem(c),
			},
		},
	}
}
```

The DrawSystem :
```golang
type DrawSystem struct {
	query *query.Query
}

func NewDrawSystem(g *core.Core) *DrawSystem {
	return &DrawSystem{
		query: query.NewQuery(filter.Or(
			filter.Contains(
				component.Appearance,
				component.Size,
				component.Position,
			),
			filter.Contains(
				component.Size,
				component.Position,
				component.Text,
			),
		)),
	}
}

func (s *DrawSystem) Draw(c *core.Core, w *donburi.World, screen *ebiten.Image) {

	lo.ForEach(
		ZSortedEntries(*w, s.query),
		func(entry *donburi.Entry, index int) {
			appearance := component.GetAppearance(entry)
			position := component.GetPosition(entry)
			// TODO: 1️⃣ look into how to get text without panic
			text := component.GetText(entry)
			size := component.GetSize(entry)

			if appearance.Image == nil {
				return
			}

			// Draw frames
                        frame := *appearance.Frames[appearance.Frame]
                        frameImage := appearance.Image.SubImage(frame).(*ebiten.Image)
			options := &ebiten.DrawImageOptions{}
			options.GeoM.Translate(position.X, position.Y)
			screen.DrawImage(frameImage, options)

			if text == nil {
				return
			}

                        // do text rendering things.
                       ...
               })
}

...

```

Problem is 1️⃣ , not all entities have text or appearance.

**Comment by airtonix** [comment]
I"m happy to submit a concept PR and take any direction from you on that.

**Comment by yohamta** [comment]
@airtonix Thank you for the suggestion and the detailed explanation!

I think that makes a lot of sense. At this point, however, it is not clear how to check for the presence of a component without overhead: checking the `ComponentLayout` will check for the presence of a component for an entity, but doing so for all entities could result in a big overhead, I think. If we can figure out a better way to implement this, API changes for this would be very welcome :)

As for the use case you described, the [HasComponent](https://pkg.go.dev/github.com/yohamta/donburi#Entry.HasComponent) method could be useful :) What do you think?

**Comment by airtonix** [comment]
@yohamta derp... i literally just found that... I feel so dumb lol. 

Love what you're doing here btw.

Being new to game development, it's becoming apparent that performance is one of the highest priorities.

As I progress through my project I'll keep in mind wether we really need to solve this problem (or if perhaps we can solve it with more additions to documentation)

**Comment by airtonix** [comment]
last thought (and tell me if this is not a great idea, or how it makes you feel) : 

```golang
func (cs *SimpleStorage) Component(archetypeIndex ArchetypeIndex, componentIndex ComponentIndex) unsafe.Pointer {
	return cs.storages[archetypeIndex][componentIndex]
}
```

can we do this? : 

```
func (cs *SimpleStorage) Component(archetypeIndex ArchetypeIndex, componentIndex ComponentIndex) (unsafe.Pointer, error) {
  archetypeCount := len(cs.storages)
  if (archetypeIndex >= archetypeCount) {
    return nil, fmt.Errorf("tried to access non existant archetype")
  }

  archetype := cs.storages[archetypeIndex]
  archetypeComponentCount = len(archetype)
  if (componentIndex >= archetypeComponentCount) {
    return nil, fmt.Errorf("tried to access non existant component on archetype")
  }

  return archetype[componentIndex], nil
}
```

I'm probably missing something about how you've architected Donburi.

(I'm totally happy with using `HasComponent` for now)

**Comment by yohamta** [comment]
@airtonix Thank you very much for the suggestion and the code!

Here is my personal opinion: if you are building a game in a language that is compiled, runtime errors are usually fatal, so once built, errors like null pointers (or SEGV) should not happen. So, personally, I am not sure exactly what specific use case you want to catch these runtime errors. If you add an error return value to a component method, the user has to check for it, but usually there is no way to deal with errors, if any, while the game is running.

If there is a reason why we would want to check for cases where a component cannot be retrieved at runtime with an error, we want to think about what API would be most convenient for developers :) I was thinking that we would probably need `MustGet` as well as `Get` in that case.

**Comment by airtonix** [comment]
👍🏻  thanks.

If it becomes problematic I'll follow up in a future ticket.

**Comment by yohamta** [comment]
Sure, thank you very much! 👍
