### ISSUE TITLE
Project Suggestion

### ISSUE THREAD

**Issue by joelschutz** [yohamta/donburi#104]
I create a game using the library, is very simple and not that fun. If you find it worth, please to the projects list.

Game page: https://kam1sama.itch.io/goingo
Source Code: https://github.com/joelschutz/goingo

**Comment by yohamta** [comment]
Hi @joelschutz , thank you for the suggestion!

I tried to run the game, but it doesn't seem to be runnable with my Mac. Would you mind providing a Mac OS version please?

Thanks a lot!

**Comment by joelschutz** [comment]
I'm still having problem cross-compiling it to MacOS, but I managed to compile a WASM version that you can check-out in my blog:

https://joelschutz.github.io/devlog/en/demo/2023/05/05/goingo-wasm-demo.html

**Comment by yohamta** [comment]
Added it, thanks!
