### ISSUE TITLE
Version confusion.

### ISSUE THREAD

**Issue by setanarut** [yohamta/donburi#149]
The latest version is `v1.15.3` on [pkg.go.dev](https://pkg.go.dev/github.com/yohamta/donburi@v1.15.3?tab=versions). However, the `v1.15.3` branch is gone. The latest release is v1.5.1 on the Github repository.

https://github.com/yohamta/donburi/tree/v1.15.3/go.mod (link is dead)

![Ekran Resmi 2024-09-25 04 52 10](https://github.com/user-attachments/assets/782dfbf0-0d08-48f3-8854-9dcb533d311b)

**Comment by yohamta** [comment]
Thank you for opening the issue. It seems my mistake. Let me retract `v1.15.2` and `v1.15.3`.

**Comment by setanarut** [comment]
@yohamta To fix it you have to release a new version like v1.5.2 `go get -u` command still downloads v1.15.3.

**Comment by yohamta** [comment]
@setanarut Thank you for letting me know. To avoid any confusion, I’ve created a tag for `v1.15.4`. Let's use this as the latest version.
